### PR TITLE
version version3

### PR DESCRIPTION
**Pull request by tygard**
Changed the version from `version3` to `3.0.0`

### CODE REVIEW

**Comment by TrevorBrunette** [comment]
Please choose a better version name. `3.0.0` does not make sense since versions are not iterable in that way.

**Comment by BryanFriestad** [comment]
Looks good to me. +1

**Comment by BryanFriestad** [comment]
> Please choose a better version name. `3.0.0` does not make sense since versions are not iterable in that way.

Looks like it's the "API version" maybe just "3" is sufficient? But having subversions for trials and such would be good, right? "3.0"?

**Review by johnnyapol — APPROVED** [review]

**Review by TrevorBrunette — CHANGES_REQUESTED** [review]
No sub-version identifier please. `3`, `v3`, `wd-3`, or some other descriptive name should be chosen. Consider renaming `version` to `edition` or something more descriptive.

**Review by johnnyapol — APPROVED** [review]

**Pull request closed without merging**
